### ISSUE TITLE
Foreign library installation failure

### ISSUE THREAD

**Issue by conal** [AccelerateHS/accelerate-llvm#10]
I ran into trouble installing the required foreign libraries Mac OS 10.11.6 via the [installation instructions](https://github.com/AccelerateHS/accelerate-llvm#installation):

```
bash-3.2$ brew update
Updated 5 taps (caskroom/cask, homebrew/boneyard, homebrew/core, homebrew/dupes, homebrew/versions).
...
bash-3.2$ brew install libffi
Warning: libffi is a keg-only and another version is linked to opt.
Use `brew install --force` if you want to install this version
bash-3.2$ brew install homebrew/versions/llvm35 --all-targets
brew install homebrew/versions/llvm35 --all-targets
Error: No available formula with the name "homebrew/versions/llvm35" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
```

**Comment by tmcdonell** [comment]
Huh. It appears that Homebrew has removed the llvm-3.5 formula.

It looks like they still have llvm-3.8 (llvm@3.8) and llvm-3.9 (llvm) though. The `stack-8.0.yaml` file is currently set up to install against llvm-3.8 (or a one-line change to use llvm-3.9), so I'd recommend trying that.

```
ln -s stack-8.0.yaml stack.yaml
stack build
```

I'll actually try if that works now though and get back to you.

Sorry this has not gone smoothly for you \\:

**Comment by tmcdonell** [comment]
Looks like this is where llvm-3.5 was dropped: https://github.com/Homebrew/homebrew-core/pull/7557

**Comment by tmcdonell** [comment]
Also it looks like the llvm@3.8 formula no longer has the `--with-all-targets` option. I'll see if I can send them a patch to fix this.

**Comment by tmcdonell** [comment]
https://github.com/Homebrew/homebrew-core/pull/9212

**Comment by tmcdonell** [comment]
Things should be easier now. I'm going to manage custom homebrew formula myself to avoid the above. Try this:

```sh
$ brew install llvm-hs/homebrew-llvm/llvm-4.0
$ ln -s stack-8.0.yaml stack.yaml
$ stack setup
$ stack build
```

**Comment by tmcdonell** [comment]
Let me know if you still have trouble. I think the above should work cleanly. Sorry again for the hassle.
