### ISSUE TITLE
Switch to llvm-hs

### ISSUE THREAD

**Issue by zmactep** [AccelerateHS/accelerate-llvm#16]
Hi!

First of all, thank you for accelerate framework. It is really great and helps in my tasks.

As most of users I'd like to see `accelerate` and it's backends on hackage. As I know the main barrier is `llvm-general` library. But now `llvm-hs` is on [hackage](https://hackage.haskell.org/package/llvm-hs), and as it is a fork, I think the replacement should not be very hard.

**Comment by tmcdonell** [comment]
Hi!

Yes, I have already done the work in [a branch](https://github.com/tmcdonell/accelerate-llvm/tree/wip/llvm-hs), and will try to finalise and release [everything](https://github.com/tmcdonell-bot/accelerate-travis-buildbot) in the next few days. (:
