### ISSUE TITLE
Feature: Provide disk caching for compiled kernels

### ISSUE THREAD

**Issue by cpdurham** [AccelerateHS/accelerate-llvm#17]
Like in accelerate-cuda

**Comment by tmcdonell** [comment]
This is a little tricky for the CPU backend, but should be in 1.1.

**Comment by tmcdonell** [comment]
On-disk caching is now available in this branch: https://github.com/tmcdonell/accelerate-llvm/tree/wip/rtdyld

There are quite a few changes in there, so I'd be good to know it all still works before merging into master.

**Comment by cpdurham** [comment]
This is great news! I'll get around to testing it this weekend!

**Comment by tmcdonell** [comment]
This is in master now \\o/

**Comment by tmcdonell** [comment]
Now part of the 1.1.0.0 release on Hackage.
