### ISSUE TITLE
Really long compilation time compared to earlier accelerate-cuda

### ISSUE THREAD

**Issue by cpdurham** [AccelerateHS/accelerate-llvm#20]
Took a while to vet this out, wanted to make sure it didn't have anything to do with some threading issues...

Anyway, I have some code that takes takes a 3d array and pretty much does a 2d convolve on each slice for an nxm kernel with an nxm stride and aggregates the "bins" with an associative function.

So a 2x4x4 becomes a 2x2x2 with n,m = 2

This code used to run fine with accelerate-cuda, but noticed it lagged a ton with the new llvm-ptx. 

Here's a gist: https://gist.github.com/cpdurham/10b43d0ae635261785dac31f37aca3f4

Ran it with 
```
time test-exe +ACC -ddump-cc -dverbose -ddump-gc -ddump-sharing -ddump-phases -ACC > out.log 2>&1

real	3m44.432s
user	3m44.296s
sys	0m0.128s
```
First case, 4x4 happens immediately though. I suspect it has something to do with the list generation, maybe its specializing the code per element in the matrix?

I included the out file and the line where it stutters is 1178

For kicks I also included my fixed function that doesn't use lists and runs just fine

Edit: Forgot to add, it's no big deal to code around this, just wanted to put it out there in case it was illuminating something wrong with the code generation. Think I got this list style from some accelerate code I read in the examples code.

**Comment by tmcdonell** [comment]
> Line [1179](https://gist.github.com/cpdurham/10b43d0ae635261785dac31f37aca3f4#file-out-log-L1179): [ 224.368] phase array-fusion: 223.811 s (wall), 223.804 s (cpu)

This seems to be the culprit. Thanks for the really comprehensive test case!

Off hand I'm not sure exactly why, but something in the fusion/simplifier phase seems to be doing a lot more work. Interestingly the 4x4 version is a much more reasonable [460 ms](https://gist.github.com/cpdurham/10b43d0ae635261785dac31f37aca3f4#file-out-log-L413), so that is an enormous blowup indeed.

Probably related: AccelerateHS/accelerate#272.

**Comment by tmcdonell** [comment]
```
ghci> setFlags [dump_phases, dump_simpl_stats, dump_simpl_iterations]
ghci> superStencil3 binDim4x4 (+) (use arr3)
[  53.205] phase sharing-recovery: 2.853 ms (wall), 2.878 ms (cpu)
[  53.205] simpl-iters/init     [0]: terms = 49, types = 2, lets = 3, vars = 8, primops = 2
[  53.205] simpl-iters/init     [0]: terms = 49, types = 2, lets = 3, vars = 8, primops = 2
[  53.205] simpl-iters/init     [0]: terms = 340, types = 50, lets = 15, vars = 95, primops = 25
[  53.349] simpl-iters/simplify [1]: terms = 326, types = 46, lets = 15, vars = 95, primops = 23
[  53.554] simpl-iters/shrink   [1]: terms = 322, types = 46, lets = 13, vars = 93, primops = 23
[  53.702] simpl-iters/simplify [1]: terms = 322, types = 46, lets = 13, vars = 93, primops = 23
[  53.205] simpl-iters/init     [0]: terms = 322, types = 46, lets = 13, vars = 93, primops = 23
[  54.052] simpl-iters/simplify [1]: terms = 322, types = 46, lets = 13, vars = 93, primops = 23
[  54.266] phase array-fusion: 1.067 s (wall), 1.064 s (cpu)
[  54.271] Total ticks: 309

2 Inline 2 Var
20 RuleFired
  8 commutes +
  6 CSE
  2 commutes *
  2 x+0
  1 aletD/float
  1 generateD
282 Substitution
  275 weakenE
  5 shrink exp
  2 inline
5 SimplifierDone 5
<...>

ghci> superStencil3 binDim5x5 (+) (use arr3)
[  56.221] phase sharing-recovery: 4.583 ms (wall), 4.584 ms (cpu)
[  56.221] simpl-iters/init     [0]: terms = 49, types = 2, lets = 3, vars = 8, primops = 2
[  56.221] simpl-iters/init     [0]: terms = 49, types = 2, lets = 3, vars = 8, primops = 2
[  56.222] simpl-iters/init     [0]: terms = 484, types = 72, lets = 17, vars = 142, primops = 36
[ 120.621] simpl-iters/simplify [1]: terms = 470, types = 68, lets = 17, vars = 142, primops = 34
[ 215.594] simpl-iters/shrink   [1]: terms = 466, types = 68, lets = 15, vars = 140, primops = 34
[ 283.431] simpl-iters/simplify [1]: terms = 466, types = 68, lets = 15, vars = 140, primops = 34
[  56.222] simpl-iters/init     [0]: terms = 466, types = 68, lets = 15, vars = 140, primops = 34
[ 450.406] simpl-iters/simplify [1]: terms = 466, types = 68, lets = 15, vars = 140, primops = 34
[ 550.080] phase array-fusion: 493.773 s (wall), 493.863 s (cpu)
[ 550.084] Total ticks: 396

2 Inline 2 Var
22 RuleFired
  10 commutes +
  6 CSE
  2 commutes *
  2 x+0
  1 aletD/float
  1 generateD
367 Substitution
  360 weakenE
  5 shrink exp
  2 inline
5 SimplifierDone 5
<...>
```

Seems to be spending a lot of time in the simplifier, but doesn't record doing much useful work. Hmm.

**Comment by cpdurham** [comment]
Oh interesting, does that mean that this is an actual accelerate issue not llvm?

**Comment by tmcdonell** [comment]
That is my suspicion, yes.

**Comment by cpdurham** [comment]
I wrote a linear version (lmk if you want it), scaling goes:
```
16: 0.05187s
17: 0.096395s
18: 0.182115s
19: 0.353874s
20: 0.69448s
21: 1.369123s
22: 2.737918s
23: 5.425754s
24: 10.744195s
25: 21.540001s
```
so 4x4 is 16 saved params, 5x5 is 25 obviously, so the extra dimension is definitely adding another factor to it

**Comment by tmcdonell** [comment]
I wrote a crappy compiler; perfect exponential blowup:

![scaling](https://cloud.githubusercontent.com/assets/728113/26086903/f0c847ec-3a30-11e7-849f-bd2452e1e87d.png)

Having the linear version would be good actually; it would be easy to see once this is fixed.

**Comment by cpdurham** [comment]
I'm the smartest one here apparently, took one compiler course in college and said "aww hell no" :)

updated the gist as OneDimMain.hs (gist requires unique file names...)

**Comment by tmcdonell** [comment]
haha, yep I'll pay that 😂

Thanks for the test case! Not sure when I'll get to this though, it could be tricky.

**Comment by cpdurham** [comment]
haha, yeah np, no rush! Just happy I was finally able to narrow it down eventually. I like the new version of my function better also.

**Comment by tmcdonell** [comment]
I made a few changes and I think that this is fixed now (or at least, manages to avoid this particular case of blowup). The 5x5 bin completes in ~8ms for me now, a 25x25 bin is ~600ms.

**Comment by cpdurham** [comment]
Great to hear!!
