### ISSUE TITLE
Mandelbrot example locks up system after giving internal error (requires manual reboot) on a K80

### ISSUE THREAD

**Issue by roboguy13** [AccelerateHS/accelerate-llvm#24]
I'm trying to run the Mandelbrot example on a computer with CentOS 7 with a Nvidia K80, using the llvm-ptx backend.

It worked for a while, but after several minutes of zooming in and out and going through the presets, it got `CUDA exception: unknown error`. The error occurs on line 50 of Data.Array.Accelerate.LLVM.PTX.State. After this happens, the system freezes (no response from the keyboard or mouse and it also cannot be ssh'd into) and must be manually rebooted.

I first noticed this what I believe is the same issue when I was running a larger Accelerate application on this machine that I am working on. It crashed after around the same amount of time of computation. In both cases, the errors are `unknown errors` that originate on line 50 of the same `accelerate-llvm-ptx` module. Also, in both cases, the two programs produce correct output for a while and it takes several minutes before the crash occurs.

I have a different machine that this larger application runs fine on (that machine has a GeForce GT 710). I haven't tested the Mandelbrot example, but I suspect it runs fine as well.

I haven't run the Mandelbrot example through `cuda-memcheck` yet but, if it's the same issue in both programs, in the larger application there are two errors logged by `cuda-memcheck`. Both of them say `CUDA_ERROR_UNKNOWN (error 999) due to "unknown error"`. The first one is on a call to `cuMemFreeHost` and the second one (I assume the one causing the crash) is on a call to `cuEventDestroy_v2`.

Incidentally, I don't know if this is relevant, but the machine that is having the issue also has a GeForce GT 710 (for running the actual display). During my test of the Mandelbrot example, I verified that it was in fact running on the K80 though, with `nvidia-smi`. A minute or so after I ran `nvidia-smi` was when the crash occurred, I believe.

Thanks and let me know if there's any more info that you'd like me to provide!

**Comment by tmcdonell** [comment]
Hm, this looks like it could be difficult to track down ):

I'm a little surprised that the system completely locks up for you, particularly because you aren't using the same card to drive the display.

Is the other machine (with the 710) also running CentOS 7?

**Comment by roboguy13** [comment]
We readjusted some of the configuration and it doesn't lock up now, but it appears to crash with the same error.

The other machine, the one with the 710, is running Fedora 25. I've also tried it (the program I'm working on) on a third machine, running Fedora 24 with a Nvidia K20. It works on that one as well.

**Comment by roboguy13** [comment]
This was on our end. The GPU was not getting proper ventilation, it was overheating and the crash was essentially the safety kicking in to prevent damage.

Sorry about that!

**Comment by tmcdonell** [comment]
No worries, glad you found the problem!
