### ISSUE TITLE
RTLD_NEXT error

### ISSUE THREAD

**Issue by skynet1** [AccelerateHS/accelerate-llvm#31]
I am submitting a...
- [x] bug report
- [ ] feature request
- [ ] support request => you might also like to ask your question on the [mailing list](mailto:accelerate-haskell@googlegroups.com) or [gitter chat](https://gitter.im/AccelerateHS/Lobby).

## Description
Running the following code in ghci:
```haskell
import Data.Array.Accelerate as A

import Data.Array.Accelerate.LLVM.Native as N

let xs = use (fromList (Z:.10) (Prelude.take 10 [0..]) :: Vector Double)

let ys = use (fromList (Z:.10) (Prelude.take 10 [0..]) :: Vector Double)

run $ A.zip xs ys
```

causes it to give the error

```
*** Exception: RTLD_NEXT not available
```

## Expected behaviour
The library should zip up the two arrays.

## Current behaviour
The library gives an RTLD_NEXT error. This only happens for LLVM.Native, and not for the Interpreter

## Steps to reproduce (for bugs)

 1.
 2.
 3.

## Your environment
Debian version 8 on amd64

- Version used:
- Backend(s) used and version: LLVM.Native version 1.1.0.1
- Operating system and version: Debian 8.0
- Link to your project:
- If this is a bug with the GPU backend, include the output of `nvidia-device-query`:

**Comment by tmcdonell** [comment]
What version of GHC are you using? Try upgrading to 8.2 if you aren't using that already?

**Comment by tmcdonell** [comment]
Otherwise, this should be fixed in the version on GitHub, you could try using that instead until I can organise the next release (there are still a few things I want to get done for that).

**Comment by skynet1** [comment]
I'm using 7.10.3

**Comment by tmcdonell** [comment]
Did either of my suggestions help?

**Comment by skynet1** [comment]
Yes
