### ISSUE TITLE
thread blocked indefinitely in an MVar operation

### ISSUE THREAD

**Issue by lehins** [AccelerateHS/accelerate-llvm#32]
I am submitting a...
- [x] bug report
- [ ] feature request
- [ ] support request => you might also like to ask your question on the [mailing list](mailto:accelerate-haskell@googlegroups.com) or [gitter chat](https://gitter.im/AccelerateHS/Lobby).

## Description
I was trying to benchmark [massiv](https://github.com/lehins/massiv) against accelerate and discovered a deadlock. Naturally, my first thought was that it is my fault, except the only time the deadlock occurred was when doing benchmarks in conjunction with `accelerate-llvm-native`. After debugging `massiv` for a few hours I was sure it is not the cause problem, despite that the error `thread blocked indefinitely in an MVar operation` is risen during the massiv benchmark. In order to prove it, removed `massiv`out of the picture and replaced it with Repa and sure enough deadlock persisted.

## Expected behaviour
No deadlock

## Current behaviour
```
Running 1 benchmarks...
Benchmark accelerate: RUNNING...
benchmarking Sum/Repa DIM2 U
time                 9.454 ms   (9.192 ms .. 9.924 ms)
                     0.984 R²   (0.971 R² .. 0.994 R²)
mean                 9.348 ms   (9.157 ms .. 9.606 ms)
std dev              626.3 μs   (443.8 μs .. 868.7 μs)
variance introduced by outliers: 34% (moderately inflated)
             
benchmarking Sum/Accelerate DIM2
time                 2.518 ms   (2.393 ms .. 2.628 ms)
                     0.955 R²   (0.927 R² .. 0.973 R²)
mean                 2.487 ms   (2.354 ms .. 2.656 ms)
std dev              502.8 μs   (416.5 μs .. 622.7 μs)
variance introduced by outliers: 90% (severely inflated)
             
benchmarking Sum/Repa DIM2 U
time                 9.648 ms   (9.411 ms .. 9.871 ms)
                     0.994 R²   (0.990 R² .. 0.997 R²)
accelerate: thread blocked indefinitely in an MVar operation
Benchmark accelerate: ERROR
Completed 2 action(s).
```

## Possible solution (optional)
My guess is that this bug has something to do with the global gang, just because there is a similar global scheduler in massiv as well. But that is just a guess. Criterion might play a factor in that too, not quite sure of that either.

## Steps to reproduce (for bugs)
```haskell
{-# LANGUAGE FlexibleContexts #-}
module Main where

import           Criterion.Main
import           Data.Array.Accelerate             as A
import           Data.Array.Accelerate.LLVM.Native as A
import           Data.Array.Repa                   as R
import           Data.Functor.Identity
import           Prelude                           as P

accArrLightDIM2 :: (Int, Int) -> A.Array A.DIM2 Double
accArrLightDIM2 (m, n) = A.fromFunction (A.Z A.:. m A.:. n) (\ (A.Z A.:. i A.:. j) -> lightFunc i j)

lightFuncExp :: Exp Int -> Exp Int -> Exp Double
lightFuncExp i j =
  A.sin (A.fromIntegral (i A.^ (2 :: Exp Int) + j A.^ (2 :: Exp Int)) :: Exp Double)

sumAccArr :: (A.Elt e, A.Shape t, P.Num (Exp e)) => A.Array t e -> e
sumAccArr = (`indexArray` A.Z) . run . A.sum . A.flatten . use

lightFunc :: Int -> Int -> Double
lightFunc i j = sin (P.fromIntegral (i P.^ (2 :: Int) + j P.^ (2 :: Int)) :: Double)

tupleToSh2 :: (Int, Int) -> R.DIM2
tupleToSh2 (i, j) = R.Z R.:. i R.:. j

arrDLightSh2 :: R.DIM2 -> R.Array D R.DIM2 Double
arrDLightSh2 sz = R.fromFunction sz (\(R.Z R.:. i R.:. j) -> lightFunc i j)

main :: IO ()
main = do
  let t2 = (1600, 1200) :: (Int, Int)
      repaArr = computeUnboxedS (arrDLightSh2 (tupleToSh2 t2))
      accArr = accArrLightDIM2 t2
  defaultMain
    [ bgroup
        "Sum"
        [ bench "Repa DIM2 U" $ whnf (runIdentity . R.sumAllP) repaArr
        , bench "Accelerate DIM2" $ whnf sumAccArr accArr
        , bench "Repa DIM2 U" $ whnf (runIdentity . R.sumAllP) repaArr
        ]
    ]
```
* Build using stack with `-threaded -O2 -with-rtsopts=-N7` GHC flags.
* Order of benchmarks is important: Repa->Accelerate->Repa, otherwise everything is cool.
* Here is a [separate branch](https://github.com/lehins/massiv/blob/accelerate-deadlock/massiv-bench/bench/Accelerate.hs) in `massiv` repo that contains the reproducible code

## Your environment

- Version used: `accelerate-llvm-native-1.1.0.1`
- Backend(s) used and version: `libffi-dev` and `llvm-5.0-dev` are installed using `apt-get`
- GHC version: `The Glorious Glasgow Haskell Compilation System, version 8.2.2`
- Operating system and version: Ubuntu 16.04
- Link to your project: [massiv](https://github.com/lehins/massiv)
- If this is a bug with the GPU backend, include the output of `nvidia-device-query`: nope, GPU isn't involved

**Comment by tmcdonell** [comment]
Hi! Congratulations on the first release!

This is great. I have wanted to benchmark against `massiv` for a while now but never found the time.

I guess this is a problem in how the thread gang is handled in repa. For example the following works:

```
$ stack bench massiv-bench:accelerate --benchmark-arguments="+RTS -N -RTS"
```

or equivalently changing the .cabal file to `-with-rtsopts=-N`.

Is there are reason to set it to `-N7` exactly?

**Comment by lehins** [comment]
Thank you! :)
> I guess this is a problem in how the thread gang is handled in repa. 
Maybe you are right, but I think there might be something more complicated than just a naive repa's scheduler at hand.
Reason for `-N7` in my case is very simple, I have a quad core with hyperthreading, so it looks like 8 capabilities to RTS. Leaving one over for the OS turns out to be a golden middle and in my case is usually faster than `-N8` (i.e. `-N`) or `-N6`.

**Comment by tmcdonell** [comment]
By the way, it is recommended to use [`runN`](http://hackage.haskell.org/package/accelerate-llvm-native-1.1.0.1/docs/Data-Array-Accelerate-LLVM-Native.html#v:runN) whenever possible, so you should probably change the `sumAccArr` function to:

```haskell
sumAccArr = (`indexArray` A.Z) . runN (A.sum . A.flatten)
```

**Comment by tmcdonell** [comment]
By the way, did you see the comment at the top of the [docs](http://hackage.haskell.org/package/accelerate-llvm-native-1.1.0.1/docs/Data-Array-Accelerate-LLVM-Native.html) regarding the `ACCELERATE_LLVM_NATIVE_THREADS` environment variable?

This also works (without changing the .cabal file):

```
$ env ACCELERATE_LLVM_NATIVE_THREADS=7 stack bench massiv-bench:accelerate 
```

But, actually, for such trivial programs, sometimes it is better to not bother with parallelism at all... (Intel Core i7-3720QM CPU, 4C/8T):

```
$ > env ACCELERATE_LLVM_NATIVE_THREADS=1 stack bench massiv-bench:accelerate --benchmark-arguments="+RTS -N7 -RTS"
massiv-bench-0.1.0.0: benchmarks
Running 1 benchmarks...
Benchmark accelerate: RUNNING...
benchmarking Sum/Repa DIM2 U
time                 8.398 ms   (7.950 ms .. 8.864 ms)
                     0.970 R²   (0.952 R² .. 0.983 R²)
mean                 9.129 ms   (8.740 ms .. 9.567 ms)
std dev              1.095 ms   (856.1 μs .. 1.404 ms)
variance introduced by outliers: 64% (severely inflated)

benchmarking Sum/Accelerate DIM2
time                 933.2 μs   (924.6 μs .. 941.1 μs)
                     0.999 R²   (0.999 R² .. 1.000 R²)
mean                 929.0 μs   (923.8 μs .. 935.0 μs)
std dev              18.52 μs   (13.85 μs .. 26.76 μs)
variance introduced by outliers: 10% (moderately inflated)
```

**Comment by tmcdonell** [comment]
(oops forgot the second part)

vs running in parallel:

```
> env ACCELERATE_LLVM_NATIVE_THREADS=7 stack bench massiv-bench:accelerate --benchmark-arguments="+RTS -N7 -RTS"
massiv-bench-0.1.0.0: benchmarks
Running 1 benchmarks...
Benchmark accelerate: RUNNING...
benchmarking Sum/Repa DIM2 U
time                 8.199 ms   (7.739 ms .. 8.770 ms)
                     0.971 R²   (0.945 R² .. 0.992 R²)
mean                 8.838 ms   (8.522 ms .. 9.184 ms)
std dev              869.8 μs   (686.2 μs .. 1.206 ms)
variance introduced by outliers: 55% (severely inflated)

benchmarking Sum/Accelerate DIM2
time                 1.529 ms   (1.383 ms .. 1.642 ms)
                     0.948 R²   (0.932 R² .. 0.968 R²)
mean                 1.377 ms   (1.336 ms .. 1.441 ms)
std dev              170.2 μs   (129.4 μs .. 230.7 μs)
variance introduced by outliers: 79% (severely inflated)
```

**Comment by lehins** [comment]
Nice.Try adding massiv to it. ;) Curious to see the result.
So the environment actually `ACCELERATE_LLVM_NATIVE_THREADS` actually overrides the `--benchmark-arguments="+RTS -N7 -RTS"`, right?
Small programs like that might not get huge speed up, but they are still useful to see relative results.

**Comment by lehins** [comment]
@tmcdonell I hate to bring the bad news, but I was able to pin down the deadlock to this line:
https://github.com/AccelerateHS/accelerate-llvm/blob/1.1.0.1-native/accelerate-llvm/Control/Parallel/Meta/Worker.hs#L154

**Comment by tmcdonell** [comment]
question: is massiv supposed to print thousands of lines of this:

```
ThreadId: ThreadId 10 is doing Start withSceduler
ThreadId: ThreadId 10 is doing Submit jobs
ThreadId: ThreadId 10 is doing Wait for work
ThreadId: ThreadId 10 is doing Done with work
```

I added:

```haskell
import Data.Massiv.Array                 as M
import Bench.Massiv.Array                as M ( arrDLightIx2, tupleToIx2 )

 -- <snip>

main :: IO ()
main = do
  let
      t2 :: (Int, Int)
      t2 = (1600, 1200)
      --
      repaArr   = computeUnboxedS (arrDLightSh2 (tupleToSh2 t2))
      massivArr = computeAs U (arrDLightIx2 Par (tupleToIx2 t2))
      accArr    = accArrLightDIM2 t2
  --
  defaultMain
    [ bgroup
        "Sum"
        [ bench "Repa DIM2 U"     $ whnf (runIdentity . R.sumAllP) repaArr
        , bench "Accelerate DIM2" $ whnf sumAccArr accArr
        , bench "Repa DIM2 U"     $ whnf (runIdentity . R.sumAllP) repaArr
        , bench "Massiv U Ix2"    $ whnf M.sum massivArr
        ]
    ]
```

**Comment by lehins** [comment]
Yes, it suppose to print a crapload of stuff if it is on `accelerate-deadlock` branch, it prints all sort of debugging stuff (I though the bug was in massiv at first). Gotta either use master or download from hackage.

**Comment by lehins** [comment]
Here is a nifty trick I came up with on how to find the place where program deadlocks: https://github.com/lehins/deadlock-debug/blob/master/src/Deadlock.hs#L22
And here is how I found the cause of the problem: https://github.com/lehins/accelerate-llvm/commit/cfad3a9c8dd768ccafa451ec47efd6f1c3d76084

**Comment by tmcdonell** [comment]
Although that is the MVar in question, it is long after any accelerate code is run and seems to only be after the repa code is run (to completion) the second time? If I comment out the second repa bench in [my last message](https://github.com/AccelerateHS/accelerate-llvm/issues/32#issuecomment-367184065), the massiv bench runs fine. What I am wondering is, could this also be triggered to some other random MVar? Or is it a specific repa+accelerate interaction, when run in a very particular way (as you noted earlier the order is important). Maybe it involves criterion as well? (I believe some of its libraries also use parallelism). I don't know, this seems tricky to narrow down...

**Comment by lehins** [comment]
This is how I know were the problem is. Above code with debugging results in:
```
Running 1 benchmarks...
Benchmark accelerate: RUNNING...
benchmarking Sum/Repa DIM2 U
time                 9.051 ms   (8.480 ms .. 9.668 ms)
                     0.974 R²   (0.957 R² .. 0.994 R²)
mean                 9.196 ms   (8.863 ms .. 10.09 ms)
std dev              1.418 ms   (800.0 μs .. 2.346 ms)
variance introduced by outliers: 76% (severely inflated)
             
benchmarking Sum/Accelerate DIM2
time                 2.160 ms   (2.022 ms .. 2.351 ms)
                     0.960 R²   (0.939 R² .. 0.979 R²)
mean                 2.176 ms   (2.082 ms .. 2.290 ms)
std dev              358.1 μs   (292.5 μs .. 479.1 μs)
variance introduced by outliers: 86% (severely inflated)
             
benchmarking Sum/Repa DIM2 U
ThreadId: ThreadId 48 is doing retryCount.gangWorker.takeMVar
ThreadId: ThreadId 45 is doing retryCount.gangWorker.takeMVar
ThreadId: ThreadId 49 is doing retryCount.gangWorker.takeMVar
ThreadId: ThreadId 42 is doing retryCount.gangWorker.takeMVar
ThreadId: ThreadId 44 is doing retryCount.gangWorker.takeMVar
ThreadId: ThreadId 46 is doing retryCount.gangWorker.takeMVar
ThreadId: ThreadId 47 is doing retryCount.gangWorker.takeMVar
ThreadId: ThreadId 43 is doing retryCount.gangWorker.takeMVar
ThreadId: ThreadId 48 is doing retryCount.gangWorker.takeMVar
ThreadId: ThreadId 45 is doing retryCount.gangWorker.takeMVar
ThreadId: ThreadId 49 is doing retryCount.gangWorker.takeMVar
ThreadId: ThreadId 42 is doing retryCount.gangWorker.takeMVar
ThreadId: ThreadId 44 is doing retryCount.gangWorker.takeMVar
ThreadId: ThreadId 46 is doing retryCount.gangWorker.takeMVar
ThreadId: ThreadId 43 is doing retryCount.gangWorker.takeMVar
.......
ThreadId: ThreadId 46 is doing retryCount.gangWorker.takeMVar
ThreadId: ThreadId 43 is doing retryCount.gangWorker.takeMVar
ThreadId: ThreadId 1368 is doing retryCount.finaliseWorker.takeMVar
ThreadId: ThreadId 1368 is doing retryCount.finaliseWorker.takeMVar
.......
ThreadId: ThreadId 1369 is doing retryCount.finaliseWorker.takeMVar
ThreadId: ThreadId 1369 is doing retryCount.finaliseWorker.takeMVar
time                 10.21 ms   (9.615 ms .. 10.78 ms)
                     0.984 R²   (0.974 R² .. 0.993 R²)
accelerate: thread blocked indefinitely in an MVar operation
Benchmark accelerate: ERROR
Completed 5 action(s).
```

**Comment by tmcdonell** [comment]
Hey that is a neat trick (:

**Comment by lehins** [comment]
Yeah, this trick is like a godsend, I was pulling my hair at some point trying to track down a deadlock in massiv a while back until I used that trick.
Narrowing this stuff down is definitely tricky. It's not only Repa, exactly the same behavior happens when used together with massiv.

**Comment by lehins** [comment]
@tmcdonell If you'd like, I could move massiv's scheduler into a separate package, so you could incorporate it in accelerate. Let me know. For now I need to get some sleep, its 5am for me.

**Comment by tmcdonell** [comment]
Yes, you should definitely sleep! Good talking to you (:

**Comment by tmcdonell** [comment]
using `massiv`'s scheduler might not be a bad idea. I had started to look at the thread scheduler I was using recently as I noticed it is actually quite slow. I'll have a look and see if your design can be adapted for use with accelerate, and if so then it would be great to be in a separate package we can reuse (:

**Comment by tmcdonell** [comment]
I am amazed you got such good performance out of ghc. I have been kind of disappointed in `repa` for a while, and barely benchmark against it anymore. Having some actual competition here will be great (though it does make my job more difficult now 😅)

**Comment by lehins** [comment]
I was amazed too, but it took a lot of work and a lot of benchmarking. The most surprising things in GHC would have negative affect on performance, so I always had to watch out for any regressions when making  changes to the code. Repa's performance was the driving factor for me starting work on massiv in the first place. But now you'll have something to benchmark accelerate against ;)

**Comment by tmcdonell** [comment]
Yeah, Ben had a lot of trouble with fragility of GHC optimisations too. I am curious how that plays out for you too, as you expand the API and write larger programs. At least it is starting at the right place! (:

**Comment by tmcdonell** [comment]
Following up, this is a problem in criterion. If you run the programs in this order outside of criterion, everything works fine.

(I have had criterion non-deterministically give me the same error in other contexts; it is interesting that it consistently happens with this setup, however.)
