### ISSUE TITLE
Documentation: installing homebrew llvm

### ISSUE THREAD

**Issue by sebeaumont** [AccelerateHS/accelerate-llvm#35]
The readme says to install 
```brew install llvm-hs/homebrew-llvm/llvm-6.0```
but I have:
```brew instal llvm-hs/llvm/llvm-6.0```
are these the same (if not what's the difference) and what are the implications of having the one over the other?

**Comment by tmcdonell** [comment]
Both versions are the same, this appears to be a convenience feature of homebrew to ignore the "homebrew-" prefix: https://docs.brew.sh/Taps

I guess we should make the documentation consistent across the packages though, thanks for pointing that out.

**Comment by sebeaumont** [comment]
Thanks. That's good to know.
