### ISSUE TITLE
Docker image system and ghc libffi version mismatch

### ISSUE THREAD

**Issue by NickHu** [AccelerateHS/accelerate-llvm#38]
I am submitting a...
- [X] bug report
- [ ] feature request
- [ ] support request => you might also like to ask your question on the [mailing list](mailto:accelerate-haskell@googlegroups.com) or [gitter chat](https://gitter.im/AccelerateHS/Lobby).

## Description

Hello, when using the Docker image, it seems that the version of libffi that ghc is compiled against (7) mismatches the version installed on the base system (based on Ubuntu 16.04 LTS, which packages libffi 6).

## Expected behaviour

Compilation inside a Docker container provided by this repository yields binaries with no missing shared libraries.

## Current behaviour

Compiling the following example:
```haskell
import Data.Array.Accelerate as A
import Data.Array.Accelerate.LLVM.Native as I

dotp :: Acc (Vector Float) -> Acc (Vector Float) -> Acc (Scalar Float)
dotp xs ys = A.fold (+) 0 (A.zipWith (*) xs ys)

main :: IO ()
main = do
  print . I.run $ dotp (A.use $ A.fromList (Z :. 10) [1..10]) (A.use $ A.fromList (Z :. 10) [2..11])
```
by `stack ghc -- hello.hs` yields an executable, and the output of `ldd` is

```
        linux-vdso.so.1 =>  (0x00007ffee4b78000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6f90911000)
        libffi.so.7 => not found
        libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f6f906e8000)
        libLLVM-6.0.so.1 => /usr/lib/x86_64-linux-gnu/libLLVM-6.0.so.1 (0x00007f6f8cbb4000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6f8c832000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f6f8c62a000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f6f8c427000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6f8c223000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6f8c006000)
        libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f6f8bd86000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6f8b9bc000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f6f90c1a000)
        libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f6f8b7b4000)
        libedit.so.2 => /usr/lib/x86_64-linux-gnu/libedit.so.2 (0x00007f6f8b57c000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f6f8b362000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6f8b14c000)
        libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f6f8af37000)
```

## Possible solution (optional)

I looked into a way to install `libffi7` but no Ubuntu distribution seems to package it! Perhaps the Debian package is okay to install, or maybe it exists in CentOS which has a Nvidia CUDA Docker image too. Alternatively, a different distribution of stack would probably fix things, but I don't know which.

## Steps to reproduce (for bugs)

 1. `docker run -it tmcdonell/accelerate-llvm`
 2. Follow as above

## Your environment

Docker image ID: `403143b154d1`

**Comment by NickHu** [comment]
Okay, installing [Debian experimental's `libffi7`](https://packages.debian.org/experimental/libffi7) seems to work as a workaround - if you are happy with this, it should be put into the Dockerfile, but it seems like a bit of a hacky fix.

**Comment by tmcdonell** [comment]
I think it should be okay to use the experimental Debian libffi7 version. Otherwise, I think you should be able to find a copy of it amongst the (internal) install files of GHC, by updating the LD_LIBRARY_PATH, but that seems even more hacky...
