### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by yongqli** [AccelerateHS/accelerate-llvm#4]
I get the following error:

    cabal install accelerate-llvm
    Resolving dependencies...
    Configuring accelerate-llvm-0.15.0.0...
    Building accelerate-llvm-0.15.0.0...
    Preprocessing library accelerate-llvm-0.15.0.0...
    [10 of 30] Compiling Data.Array.Accelerate.LLVM.CodeGen.Monad ( Data/Array/Accelerate/LLVM/CodeGen/Monad.hs, dist/dist-sandbox-c4e7e153/build/Data/Array/Accelerate/LLVM/CodeGen/Monad.o )
    Loading package ghc-prim ... linking ... done.
    Loading package integer-gmp ... linking ... done.
    Loading package base ... linking ... done.
    Loading package primitive-0.5.4.0 ... linking ... done.
    Loading package array-0.5.0.0 ... linking ... done.
    Loading package deepseq-1.3.0.2 ... linking ... done.
    Loading package old-locale-1.0.0.6 ... linking ... done.
    Loading package time-1.4.2 ... linking ... done.
    Loading package vector-0.10.12.1 ... linking ... done.
    Loading package mwc-random-0.13.2.2 ... linking ... done.
    Loading package bytestring-0.10.4.0 ... linking ... done.
    Loading package containers-0.5.5.1 ... linking ... done.
    Loading package transformers-0.3.0.0 ... linking ... done.
    Loading package mtl-2.1.3.1 ... linking ... done.
    Loading package text-1.2.0.0 ... linking ... done.
    Loading package parsec-3.1.7 ... linking ... done.
    Loading package unix-2.7.0.1 ... linking ... done.
    Loading package setenv-0.1.1.1 ... linking ... done.
    Loading package pretty-1.1.1.1 ... linking ... done.
    Loading package template-haskell ... linking ... done.
    Loading package llvm-general-pure-3.4.4.0 ... linking ... done.
    Loading package utf8-string-0.3.8 ... linking ... done.
    Loading package llvm-general-3.4.4.0 ... linking ... done.
    Loading package dlist-0.7.1 ... linking ... done.
    Loading package random-1.1 ... linking ... done.
    Loading package abstract-deque-0.3 ... linking ... done.
    Loading package atomic-primops-0.6.1 ... linking ... done.
    Loading package bits-atomic-0.1.3 ... linking ... done.
    Loading package chaselev-deque-0.5.0.3 ... linking ... done.
    Loading package fclabels-2.0.2 ... linking ... done.
    Loading package hashable-1.2.2.0 ... linking ... done.
    Loading package hashtables-1.1.2.1 ... linking ... done.
    Loading package unordered-containers-0.2.5.1 ... linking ... done.
    Loading package accelerate-0.15.0.0 ... linking ... done.

    Data/Array/Accelerate/LLVM/CodeGen/Monad.hs:180:3:
        Couldn't match type ‘Name -> Operand’ with ‘Operand’
        Expected type: CodeGen Operand
          Actual type: CodeGen (Name -> Operand)
        In a stmt of a 'do' block:
          state
          $ \ s
              -> case Seq.viewr (blockChain s) of {
                   Seq.EmptyR
                     -> \ format_a8Qh kind_a8Qi fn_a8Qj msg_a8Qk
                          -> error
                               (format_a8Qh
                                  kind_a8Qi (Data.Array.Accelerate.Error.call fn_a8Qj msg_a8Qk))
                          (\ kind_a8Ql msg_a8Qm -> ...)
                          Data.Array.Accelerate.Error.Internal
                          "instr"
                          "empty block chain"
                   bs Seq.:> b
                     -> (LocalReference name, s {blockChain = bs Seq.|> ...}) }
        In the expression:
          do { name <- freshName;
               state
               $ \ s
                   -> case Seq.viewr (blockChain s) of {
                        Seq.EmptyR -> ...
                        bs Seq.:> b -> ... } }
        In an equation for ‘instr’:
            instr op
              = do { name <- freshName;
                     state $ \ s -> ... }

    Data/Array/Accelerate/LLVM/CodeGen/Monad.hs:183:39:
        Couldn't match expected type ‘Type’ with actual type ‘Name’
        In the first argument of ‘LocalReference’, namely ‘name’
        In the expression: LocalReference name

    Data/Array/Accelerate/LLVM/CodeGen/Monad.hs:213:3:
        Couldn't match type ‘Name -> Operand’ with ‘Operand’
        Expected type: CodeGen Operand
          Actual type: CodeGen (Name -> Operand)
        In the expression:
          state
          $ \ s
              -> case Seq.findIndexR search (blockChain s) of {
                   Nothing
                     -> \ format_a8QR kind_a8QS fn_a8QT msg_a8QU
                          -> error
                               (format_a8QR
                                  kind_a8QS (Data.Array.Accelerate.Error.call fn_a8QT msg_a8QU))
                          (\ kind_a8QV msg_a8QW -> ...)
                          Data.Array.Accelerate.Error.Internal
                          "phi"
                          "unknown basic block"
                   Just i
                     -> (LocalReference crit,
                         s {blockChain = Seq.adjust (\ b -> ...) i (blockChain s)}) }
        In the expression:
          let
            op = Phi t [... | (o, Block {..}) <- incoming] []
            search this = blockLabel this == blockLabel target
          in
            state
            $ \ s
                -> case Seq.findIndexR search (blockChain s) of {
                     Nothing
                       -> \ format_a8QR kind_a8QS fn_a8QT msg_a8QU -> ...
                            (...)
                            Data.Array.Accelerate.Error.Internal
                            "phi"
                            "unknown basic block"
                     Just i -> ... }
        In an equation for ‘phi’:
            phi target crit t incoming
              = let
                  op = Phi t ... ...
                  search this = blockLabel this == blockLabel target
                in
                  state
                  $ \ s
                      -> case Seq.findIndexR search (blockChain s) of {
                           Nothing -> ...
                           Just i -> ... }

    Data/Array/Accelerate/LLVM/CodeGen/Monad.hs:216:35:
        Couldn't match expected type ‘Type’ with actual type ‘Name’
        In the first argument of ‘LocalReference’, namely ‘crit’
        In the expression: LocalReference crit
    Failed to install accelerate-llvm-0.15.0.0

**Comment by remdezx** [comment]
The same problem. With which version did it worked?

**Comment by tmcdonell** [comment]
llvm-general-pure-3.4.2.2 should work, that looks like the last version before the definition of `Operand` was changed.

**Comment by remdezx** [comment]
Unfortunately with `llvm-general-pure-3.4.2.2` there is a problem with `CodeGen/Arithmetic`

    Data/Array/Accelerate/LLVM/CodeGen/Arithmetic.hs:67:12:
        Not in scope: type constructor or class ‘FastMathFlags’
     
    Data/Array/Accelerate/LLVM/CodeGen/Arithmetic.hs:68:11:
        Not in scope: data constructor ‘UnsafeAlgebra’

Full log is here: https://gist.github.com/remdezx/2418ab707ad64b42a056
I'll try other `llvm-general` versions

**Comment by tmcdonell** [comment]
Those were two things that we had added to `llvm-general-pure`, but I didn't keep track of which release versions they first made it into --- apparently after this change to `Operand`.

I'm going to allocate some cycles to continue working on this over the next month or so.

**Comment by zgredzik** [comment]
Bump!

I've been trying to get accelerate-llvm to work and I managed it with a few workarounds:

First of all, regarding **llvm-general**:
bscarlet/llvm-general@5384be96f720dc8d8d4f88717c40c9b0cfbcc3c9 is the commit changing some structures that makes accelerate-llvm incompatible with llvm-general
bscarlet/llvm-general@e6cb6c2d076e08d4b3243a772c7f85c864b4f047 is the one right before those changes (almost compatible with accelerate-llvm)
bscarlet/llvm-general@5e660fbadc9eeb88da88097fd11c0885111a377d cherry-picking this one makes llvm-general compatible with accelerate-llvm (acc-llvm's Optimise.hs requires some fields added to PassManager in this commit)
bscarlet/llvm-general@8aa513a15ef4218b8d4c8f8c2e715151db792889 adds support for newer cabal versions, so it is good to cherry-pick this one too

Unfortunatelly, at this point one has to downgrade **accelerate** in order for it to work with accelerate-llvm (and **accelerate-io** if used):
AccelerateHS/accelerate@30c1764f9ae28c0ddddb86e918cca1f33873cb00 last commit to work with accelerate-llvm
AccelerateHS/accelerate-io@c6669dad9d92e39c5e335d948dfffed5a050b4fb *corresponding* accelerate-io commit

Finally, the only thing left to do is to modify a few lines in **accelerate-llvm** as mentioned in AccelerateHS/accelerate#180 :
```diff
diff --git a/accelerate-llvm-native/Data/Array/Accelerate/LLVM/Native/Compile/Optimise.hs b/accelerate-llvm-native/Data/Array/Accelerate/LLVM/Native/Compile/Optimise.hs
index 240ea54..6bcd5df 100644
--- a/accelerate-llvm-native/Data/Array/Accelerate/LLVM/Native/Compile/Optimise.hs
+++ b/accelerate-llvm-native/Data/Array/Accelerate/LLVM/Native/Compile/Optimise.hs
@@ -42,9 +42,9 @@ optimiseModule datalayout machine libinfo mdl = do
 
   let p1 = defaultCuratedPassSetSpec
             { optLevel                  = Just 3
-            , curatedDataLayout         = datalayout
-            , curatedTargetMachine      = machine
-            , curatedTargetLibraryInfo  = libinfo
+            , dataLayout         = datalayout
+            , targetMachine      = machine
+            , targetLibraryInfo  = libinfo
             }
   b1 <- withPassManager p1 $ \pm -> runPassManager pm mdl
```
and installing it with a constraint `--constraint=atomic-primops==0.6.1.1` (can't remember now what changed in 0.7).

I've played around a little bit with **accelerate-llvm-native** and it works.

A simple script I've made to make it easier for me to run the tests: https://gist.github.com/zgredzik/031b4376f404856c56a5
Atm it lacks including the changes that should be made to accelerate-llvm. I'll add that asap as well as a fork of llvm-general package that is set up to work with the current version of accelerate-llvm.

However, even though I think I can stick to the slightly *tuned* version of llvm-general, I'd prefer not to have to revert accelerate itself. Is there any chance @tmcdonell for you to find some spare cycles and look into the matter of moving accelerate-llvm up to date with accelerate?

**Comment by tmcdonell** [comment]
Wow, thanks for the very detailed description of what needs to be changed! I'm going to spend some time this week getting the package up and running again.

**Comment by mchakravarty** [comment]
@tmcdonell :+1: :100:

**Comment by tmcdonell** [comment]
FYI development is happening on [this branch](https://github.com/tmcdonell/accelerate-llvm/tree/dev/typed).

**Comment by pmlodawski** [comment]
great! thanks!

**Comment by tmcdonell** [comment]
This has been merged into master now. It is still missing support for many of the combinators though.
