### ISSUE TITLE
accelerate 1.3.* required, but hackage has only 1.2.0.1

### ISSUE THREAD

**Issue by jrp2014** [AccelerateHS/accelerate-llvm#43]
I am trying to build `accelerate-llvm` and `accelerate-llvm-native` (with `cabal v2-build` and the hackage version of `accelerate`, which is 1.2.0.1).  I can't do so because they're dependent on `accelerate` 1.3.*.  

What is the recommended way of getting a version of `accelerate` + LLVM cpu back end up and running, if you have reasons for not putting up a consistent set on hackage.

Thanks,.

**Comment by tmcdonell** [comment]
Did you encounter a situation where a package on Hackage requested `accelerate-1.3.*`? That isn't right... if so, which package was that?

If you are trying to build `accelerate-llvm` from GitHub, the short answer is use [`stack`](https://docs.haskellstack.org/en/stable/README/) rather than `cabal`. The code on GitHub will often require unreleased versions of packages and the easiest way to deal with those dependencies is with `stack`.

**Comment by jrp2014** [comment]
Ah.  I now see what I did.  The `accelerate-llvm-native` on Hackage requires a pre-`base-4.12` and I am using ghc-8.6.3, so I tried to build from source.  (I was trying to avoid using stack, since I don't use it in m other apps.)

**Comment by tmcdonell** [comment]
The project will still build with `cabal`, you will just need to download each of the dependencies (in this case, only `accelerate`) from GitHub yourself and build those first. `stack` just helps automate the process for me, but I don't intend to tie the project to it (with this `package.yaml` or whatever else that only it understands).

Anyway, I think this is fixed now, so closing. Let me know if you still run into problems.

**Comment by jrp2014** [comment]
Oh.  Perhaps I didn't read the documentation carefully enough, but I assumed that `accelerate` needed a `run` function from a backend to make everything go.  (I couldn't find a reference to the various run functions in the main library.)

**Comment by tmcdonell** [comment]
Yes, this is correct. The `accelerate` package defines the core language, but a backend is needed to execute the programs. The `accelerate` package includes an interpreter backend as a reference implementation, but you will want to use the CPU backend in `accelerate-llvm-native`, or the GPU backend in `accelerate-llvm-ptx`.

**Comment by jrp2014** [comment]
OK, so the underlying issue is that, unlike `accelerate`, the hackage version of `accelerate-llvm-native` has a `base` upper bound that is lower than the `base` provided by ghc 8.6.3.

**Comment by tmcdonell** [comment]
Ah, yes I see now. I got half way through releasing updates for ghc-8.6 and then got swamped with other stuff (AccelerateHS/accelerate#430)

**Comment by jrp2014** [comment]
... and if I try to build the hackage version using `cabal --allow-newer=base,containers,llvm-hs new-install accelerate-llvm-native` it builds a lot of libraries, including `accelerate`, before hitting a different issue that boils down to needing LLVM 6, not 7, being required in `Downcast.hs`.

**Comment by tmcdonell** [comment]
Yes, I believe that `llvm-hs-6.*` was never patched to work with ghc-8.6, which is where the stumbling block was. I'll try and find some time to get back to making all those patch releases...
