### ISSUE TITLE
Stencil causes artefacts

### ISSUE THREAD

**Issue by flannelhead** [AccelerateHS/accelerate-llvm#45]
I am submitting a...
- [x] bug report
- [ ] feature request
- [ ] support request => you might also like to ask your question on the [mailing list](mailto:accelerate-haskell@googlegroups.com) or [gitter chat](https://gitter.im/AccelerateHS/Lobby).

## Description

Usage of stencil to blur an image causes artefacts

## Expected behaviour

Given the source image,
![blocks](https://user-images.githubusercontent.com/5001906/60927265-f253cc80-a2b1-11e9-845b-3698e693c778.png)
the program should give this:
![blur_srgb_expected](https://user-images.githubusercontent.com/5001906/60927278-f97ada80-a2b1-11e9-8ec4-d93e2f327b2d.png)

## Current behaviour

The real outcome looks good except for a few artefacts in the upper border:
![blur_srgb](https://user-images.githubusercontent.com/5001906/60927515-e3b9e500-a2b2-11e9-9fbb-4418da5f2d11.png)

## Steps to reproduce (for bugs)

Build and run the project from [this repo](https://github.com/flannelhead/accelerate-repros/tree/master/stencil-blur-artefacts) with `stack`, using LLVM 8.0.0. The artefacts don't seem to appear at every run, so one might have to repeat.

The `fromRGB` and `toRGB` don't seem to be the cause of this - if I remove the `blur` sandwiched between these, there are no artefacts. There is not much other processing done for the image in that code.

The artefacts seem to appear at the top and bottom borders of the image. I first encountered this when writing an effect for [`blackstar`](https://github.com/flannelhead/blackstar/tree/accelerate) and there the introduction of a similar blur also caused the artifacts to appear.

The Accelerate interpreter doesn't seem to have this issue. Not tested with PTX yet.

## Your environment

- Version used: master e0f1a7676d160168440ed8338f2054014976646b, accelerate master 4c3cc28904ef4d132f97abe6932731695829e4ef (most recent that is compatible with accelerate-llvm)
- Backend(s) used and version: LLVM native with LLVM 8.0.0
- GHC version: 8.6.5
- Operating system and version: Arch Linux
- Link to your project: https://github.com/flannelhead/accelerate-repros/tree/master/stencil-blur-artefacts

**Comment by tmcdonell** [comment]
@JoshMeredith can you take a look?

**Comment by flannelhead** [comment]
I reduced this further down:
```haskell
{-# LANGUAGE FlexibleContexts #-}

module Main where

import Data.Array.Accelerate                              as A
-- import Data.Array.Accelerate.Interpreter                  as A
import Data.Array.Accelerate.LLVM.Native                  as A
import Data.Array.Accelerate.IO.Codec.BMP                 as A
import Data.Array.Accelerate.Data.Colour.RGB              as RGB

import qualified Prelude                                  as P


type Stencil5x1 a = (Stencil3 a, Stencil5 a, Stencil3 a)

convolve5x1 :: A.Fractional a => Stencil5x1 a -> Exp a
convolve5x1 (_, (a,b,c,d,e), _) = 0.2 * P.sum [a,b,c,d,e]

convolveX :: A.Fractional a => Acc (Matrix a) -> Acc (Matrix a)
convolveX = stencil convolve5x1 A.clamp

testImage :: Matrix Float
testImage = let
  f (Z :. y :. x) = if x P.< 5 then 0 else 1
  in fromFunction (Z :. 10 :. 10) f

fromScalar :: Exp Float -> Exp (RGB Float)
fromScalar x = rgb x x x

main :: P.IO ()
main = do
  let img = convolveX $ use testImage
  writeImageToBMP "out.bmp" $ run $ A.map (packRGB . fromScalar) img
```
Here a 5 pixel horizontal box convolution is applied to a 10x10 image with a vertical edge from black to white. The actual convolution is applied to a `Array DIM2 Float` (to rule out any possible effects of `RGB Float` elements).

LLVM backend produces this (scaled up for better viewing):
![out_bad](https://user-images.githubusercontent.com/5001906/61416201-9b767480-a8fb-11e9-9db8-cc37e1bc91d7.png)
Notice the grey bars near the edges. Curiously the artefacts don't appear at the edges: 2 pixels at top and bottom, 1 pixel left and right edges are free of artefacts.

Interpreter produces this (expected result):
![out_good](https://user-images.githubusercontent.com/5001906/61416214-a3361900-a8fb-11e9-8506-36981dea30ad.png)

Here is the same convolution applied using the LLVM backend on an image with a horizontal edge instead:
![out_horz](https://user-images.githubusercontent.com/5001906/61416329-f8722a80-a8fb-11e9-92a1-8706e2ea0e54.png)
Notice the grey pixels near the edge. It looks like the boundary is not properly handled and the convolution is calculated somehow across the adjacent black and white rows.

**Comment by flannelhead** [comment]
Vertical (Y) convolution gives a little bit different results:
![yconv_vert](https://user-images.githubusercontent.com/5001906/61416995-599afd80-a8fe-11e9-8817-09f30ffef37f.png)
![yconv_horz](https://user-images.githubusercontent.com/5001906/61417005-5d2e8480-a8fe-11e9-95a0-11e2452ca8d6.png)

**Comment by flannelhead** [comment]
Is there anything I could help with in order to resolve this issue? I tried had a look at the handling of boundaries in the stencil implementation but there was nothing that caught my eye yet.

**Comment by JoshMeredith** [comment]
(Sorry for the delay; I haven't forgotten about this)

My first step would probably be testing a few different versions of LLVM. There have been problems in the past relating to how LLVM's optimiser uses SIMD instructions and I'm concerned that it might be a similar issue.

**Comment by flannelhead** [comment]
@JoshMeredith thanks, I'll spin up a Docker image which should be handy for testing different versions of LLVM. A plenty of versions seem to be available as DEB packages so testing should be easy enough. I'll follow up with results.

**Comment by flannelhead** [comment]
I managed to test LLVM `6.0.1`, `7.0.1`, `8.0.1` and the shortly upcoming `9.0.0`. All of these unfortunately showed the same issue (I sincerely hope I did everything right). Testing `5.0.0.` and below turns out quite laborious since there are compatibility issues between GHC, `llvm-hs` and `accelerate` versions arising. I can still try it if necessary, but before I would like to know if the stencil code has worked properly with any of these LLVM versions.

**Comment by JoshMeredith** [comment]
Thanks for the help - I think that's enough of a range of versions to be very convincing. I'll try and test the reproduction case against my old experimental branches and report back.

**Comment by justinpastoncooper** [comment]
@tmcdonell 

I have reduced the example of @flannelhead to a case with addition of `Float`s alone, thus no V3 involvement, and no multiplication. In particular, the kernel applies a `Stencil5x1 Float` stencil, which sums each element with the two elements to the right. Outside the boundaries are constant 0s.

There are two offending inputs: a) one array formed all of 1s, and b) one array where each row is formed of decreasing powers of 2. I am not sure where 35 could be coming from in b). Note how in both cases, not the first two and last two rows are as expected, while the middle two rows are weird.

The code is a stack project at https://github.com/justinpastoncooper/accelerate-issue.

a)

input:

1	1	1	1	1	1
1	1	1	1	1	1
1	1	1	1	1	1
1	1	1	1	1	1
1	1	1	1	1	1
1	1	1	1	1	1

output:

3	3	3	3	2	1
3	3	3	3	2	1
3	3	3	3	3	1
3	3	3	3	3	1
3	3	3	3	2	1
3	3	3	3	2	1


b)

input:

32	16	8	4	2	1
32	16	8	4	2	1
32	16	8	4	2	1
32	16	8	4	2	1
32	16	8	4	2	1
32	16	8	4	2	1

output:

56	28	14	7	3	1
56	28	14	7	3	1
56	28	14	7	35	1
56	28	14	7	35	1
56	28	14	7	3	1
56	28	14	7	3	1

**Comment by justinpastoncooper** [comment]
35 is (2 + 1 + 0 + 32), where 3 is what we expected in place of 35. Is there a problem here with boundary value initialisation? The boundary here should be the constant 0.

**Comment by justinpastoncooper** [comment]
I think this is down to how the function `inside` in `accelerate-llvm-native/src/Data/Array/Accelerate/LLVM/Native/CodeGen/Stencil.hs` computes its result. I think `c` of `a + b + c` for the erroneous values in the middle rows are seen as inside when they are actually outside.
