### ISSUE TITLE
unindex2 usage with runQ causes typecheck error

### ISSUE THREAD

**Issue by flannelhead** [AccelerateHS/accelerate-llvm#47]
I am submitting a...
- [x] bug report
- [ ] feature request
- [ ] support request => you might also like to ask your question on the [mailing list](mailto:accelerate-haskell@googlegroups.com) or [gitter chat](https://gitter.im/AccelerateHS/Lobby).

## Description

Typecheck error raised from the usage of `unindex2` in code compiled with `runQ`.

## Expected behaviour

Consider this snippet:
```
prog = let
    sh = index2 10 10
    unidx = unindex2 sh :: Exp (Int, Int)
    (h, w) = unlift unidx :: (Exp Int, Exp Int)
    in A.map packRGB $ generate (index2 h w) (const $ rgb 0.1 0.1 0.1)
```
which should compile with `$( runQ prog )`.

## Current behaviour

Compilation ends in typecheck error:
```
/home/sakari/projektit/accelerate-reproductions/unindex-runq-compile-error/app/Main.hs:19:34: error:
    • Couldn't match type ‘Data.Array.Accelerate.Product.ProdRepr
                             bnd_t0’
                     with ‘(((), Int), Int)’
      Expected type: Data.Array.Accelerate.Product.TupleIdx
                       (Data.Array.Accelerate.Array.Sugar.TupleRepr bnd_t0) Int
        Actual type: Data.Array.Accelerate.Product.TupleIdx
                       (((), Int), Int) Int
      The type variable ‘bnd_t0’ is ambiguous
    • In the first argument of ‘Data.Array.Accelerate.AST.Prj’, namely
        ‘Data.Array.Accelerate.Product.ZeroTupIdx’
      In the second argument of ‘Data.Array.Accelerate.AST.IndexCons’, namely
        ‘((Data.Array.Accelerate.AST.Prj
             Data.Array.Accelerate.Product.ZeroTupIdx)
            (Data.Array.Accelerate.AST.Var Data.Array.Accelerate.AST.ZeroIdx))’
      In the second argument of ‘Data.Array.Accelerate.AST.Let’, namely
        ‘((Data.Array.Accelerate.AST.IndexCons
             ((Data.Array.Accelerate.AST.IndexCons
                 (Data.Array.Accelerate.AST.Var
                    (Data.Array.Accelerate.AST.SuccIdx
                       Data.Array.Accelerate.AST.ZeroIdx)))
                ((Data.Array.Accelerate.AST.Prj
                    (Data.Array.Accelerate.Product.SuccTupIdx
                       Data.Array.Accelerate.Product.ZeroTupIdx))
                   (Data.Array.Accelerate.AST.Var
                      Data.Array.Accelerate.AST.ZeroIdx))))
            ((Data.Array.Accelerate.AST.Prj
                Data.Array.Accelerate.Product.ZeroTupIdx)
               (Data.Array.Accelerate.AST.Var
                  Data.Array.Accelerate.AST.ZeroIdx)))’
   |
19 |   writeImageToBMP "out.bmp" $ $( runQ prog )
   |     
```
`runN` works fine in this case. On the other hand, just using `unlift` and pattern matching makes the snippet compile:
```
prog = let
    sh = index2 10 10
    Z :. h :. w = unlift sh
    in A.map packRGB $ generate (index2 (h :: Exp Int) (w :: Exp Int)) (const $ rgb 0.1 0.1 0.1)
```

## Steps to reproduce (for bugs)

Use the code from [this repo](https://github.com/flannelhead/accelerate-repros/tree/master/unindex-runq-compile-error) and build it with `stack`.

## Your environment

- Version used: master e0f1a7676d160168440ed8338f2054014976646b, accelerate master 4c3cc28904ef4d132f97abe6932731695829e4ef (most recent that is compatible with accelerate-llvm)
- Backend(s) used and version: LLVM native with LLVM 8.0.0
- GHC version: 8.6.5
- Operating system and version: Arch Linux
- Link to your project: https://github.com/flannelhead/accelerate-repros/tree/master/unindex-runq-compile-error

**Comment by tmcdonell** [comment]
Okay, thanks! I know what's going on here so this test case should help me track it down easily.

**Comment by flannelhead** [comment]
Great! Hope the reproductions I sent are useful. As they stand they're quite meaningless but they're extracted from a real application, reducing to a minimum (although I didn't try reducing the dimensionality of the `Array`s, hope that doesn't matter too much).

**Comment by flannelhead** [comment]
Seems to be fixed, thank you!
