### ISSUE TITLE
accelerate-llvm-{native,ptx} depends on llvm-hs < 8.1 on hackage

### ISSUE THREAD

**Issue by ianliu** [AccelerateHS/accelerate-llvm#56]
I am submitting a...
- [x] bug report
- [ ] feature request
- [ ] support request => you might also like to ask your question on the [mailing list](mailto:accelerate-haskell@googlegroups.com) or [gitter chat](https://gitter.im/AccelerateHS/Lobby).

## Description

I'm trying to install accelerate on my Arch Linux, which has LLVM 9.0.1, but both `accelerate-llvm-native` and `accelerate-llvm-ptx` backends depend on `llvm-hs < 8.1` on Hackage.

## Expected behaviour

I expect the package to install smoothly with cabal on my system with LLVM 9.0.1.

## Current behaviour
Installation fails with the following error:

    $ cabal new-install --lib accelerate-llvm-ptx  --constraint="llvm-hs==9.0.*"
    Resolving dependencies...
    cabal: Could not resolve dependencies:
    [__0] trying: accelerate-llvm-ptx-1.2.0.1 (user goal)
    [__1] next goal: llvm-hs (dependency of accelerate-llvm-ptx)
    [__1] rejecting: llvm-hs-9.0.1, llvm-hs-9.0.0 (conflict: accelerate-llvm-ptx => llvm-hs>=4.1 && <8.1)

## Possible solution (optional)

By inspecting the source code, I can see that they depend on `llvm-hs < 9.1` now, so I think this is just a matter of updating the Hackage library.

## Steps to reproduce (for bugs)

    cabal new-install llvm-hs -fshared-llvm --constraint="llvm-hs==9.0.*"
    cabal new-install accelerate-llvm-native --constraint="llvm-hs==9.0.*

## Your environment

- Version used:
- Backend(s) used and version: native 1.2.0.1
- GHC version: 8.6.5
- Operating system and version: Arch Linux (llvm-9.0.1-1)

**Comment by tmcdonell** [comment]
Hi @ianliu!

I've been meaning to make a new release for a while, but have just been swamped (AccelerateHS/accelerate#444). It may work if you just allow it to build with the newer version, but I haven't tried this. The GitHub versions work with LLVM-9 though, I've been using that for a while now.

**Comment by tmcdonell** [comment]
accelerate-1.3 is out now! (:
