### ISSUE TITLE
Inconsistent evaluation order for permute with the PTX backend

### ISSUE THREAD

**Issue by robbert-vdh** [AccelerateHS/accelerate-llvm#61]
I am submitting a...
- [x] bug report
- [ ] feature request
- [ ] support request

## Description
The order of evaluation for `permute` seems to be inconsistent when changing between backends and GPUs. `accelerate-llvm-native` and the interpreter always evaluate from left to right, while `accelerate-llvm-ptx` seems to evaluate from right to left when using a Turing GPU. I've tested this using two Turing GPUs and a Pascal GPU. On the Pascal GPU the evaluation was performed from left to right and yielded the expected results. Since `permute` is used in a few places to compact arrays, this can cause incorrect results on the PTX backend. I don't know if a correct order is being defined anywhere, but a few functions in Accelerate's prelude (such as `expand`) depend on permute being evaluated from left to right.

## Steps to reproduce (for bugs)
I've written a small function [here](https://gist.github.com/robbert-vdh/cd353bd70114fdd4f3872fc0e8d380cf) that demonstrates this using the same process as how `iotas` is being calculated in the `expand` function.

1. Clone to above gist to a directory.
2. Run `cabal -j run` to run with the `accelerate-llvm-ptx` backend.
3. Comment out one of the other backends in `Main.hs` to switch backends.

## Expected behaviour
Using `accelerate-llvm-native`, `Data.Array.Accelerate.Interpreter`, or `accelerate-llvm-ptx` in combination with an NVIDIA MX250 mobile Pascal GPU, this prints the following results:

```
Input:
Vector (Z :. 6) [(0,-10.0),(0,10.0),(1,20.0),(2,-30.0),(2,-40.0),(2,30.0)]

Output: (all values should be positive)
Vector (Z :. 3) [(0,10.0),(1,20.0),(2,30.0)]
```

## Current behaviour
When using `accelerate-llvm-ptx` with a Turing GPU, this prints:

```
Input:
Vector (Z :. 6) [(0,-10.0),(0,10.0),(1,20.0),(2,-30.0),(2,-40.0),(2,30.0)]

Output: (all values should be positive)
Vector (Z :. 3) [(0,-10.0),(1,20.0),(2,-30.0)]
```

## Your environment

- Version used: accelerate-1.3.0.0 / https://github.com/AccelerateHS/accelerate-llvm/commit/9289093724c5f5c6f0353ef0786d40c7abf851ac
- Backend(s) used and version: accelerate-llvm-1.3.0.0 / 9289093724c5f5c6f0353ef0786d40c7abf851ac
- GHC version: 8.10.2 (also tested on 8.8.4)
- Operating system and version: Manjaro Linux with LLVM 9.0.1
- Link to your project:
- If this is a bug with the GPU backend, include the output of `nvidia-device-query`:

<details>
<summary>nvidia-device-query for the Turing GPU</summary>

```
CUDA device query (Driver API, statically linked)
CUDA driver version 11.0
CUDA API version 10.2
Detected 1 CUDA capable device

Device 0: GeForce RTX 2080 SUPER
  CUDA capability:                          7.5
  CUDA cores:                               3072 cores in 48 multiprocessors (64 cores/MP)
  Global memory:                            8 GB
  Constant memory:                          64 kB
  Shared memory per block:                  48 kB
  Registers per block:                      65536
  Warp size:                                32
  Maximum threads per multiprocessor:       1024
  Maximum threads per block:                1024
  Maximum grid dimensions:                  2147483647 x 65535 x 65535
  Maximum block dimensions:                 1024 x 1024 x 64
  GPU clock rate:                           1.845 GHz
  Memory clock rate:                        7.751 GHz
  Memory bus width:                         256-bit
  L2 cache size:                            4 MB
  Maximum texture dimensions               
    1D:                                     131072
    2D:                                     131072 x 65536
    3D:                                     16384 x 16384 x 16384
  Texture alignment:                        512 B
  Maximum memory pitch:                     2 GB
  Concurrent kernel execution:              Yes
  Concurrent copy and execution:            Yes, with 3 copy engines
  Runtime limit on kernel execution:        Yes
  Integrated GPU sharing host memory:       No
  Host page-locked memory mapping:          Yes
  ECC memory support:                       No
  Unified addressing (UVA):                 Yes
  Single to double precision performance:   32 : 1
  Supports compute pre-emption:             Yes
  Supports cooperative launch:              Yes
  Supports multi-device cooperative launch: Yes
  PCI bus/location:                         1/0
  Compute mode:                             Default
    Multiple contexts are allowed on the device simultaneously
```
</details>

<details>
<summary>nvidia-device-query for the mobile Pascal GPU</summary>

```
CUDA device query (Driver API, statically linked)
CUDA driver version 10.2
CUDA API version 10.2
Detected 1 CUDA capable device

Device 0: GeForce MX250
  CUDA capability:                          6.1
  CUDA cores:                               384 cores in 3 multiprocessors (128 cores/MP)
  Global memory:                            2 GB
  Constant memory:                          64 kB
  Shared memory per block:                  48 kB
  Registers per block:                      65536
  Warp size:                                32
  Maximum threads per multiprocessor:       2048
  Maximum threads per block:                1024
  Maximum grid dimensions:                  2147483647 x 65535 x 65535
  Maximum block dimensions:                 1024 x 1024 x 64
  GPU clock rate:                           1.582 GHz
  Memory clock rate:                        3.504 GHz
  Memory bus width:                         64-bit
  L2 cache size:                            512 kB
  Maximum texture dimensions
    1D:                                     131072
    2D:                                     131072 x 65536
    3D:                                     16384 x 16384 x 16384
  Texture alignment:                        512 B
  Maximum memory pitch:                     2 GB
  Concurrent kernel execution:              Yes
  Concurrent copy and execution:            Yes, with 2 copy engines
  Runtime limit on kernel execution:        Yes
  Integrated GPU sharing host memory:       No
  Host page-locked memory mapping:          Yes
  ECC memory support:                       No
  Unified addressing (UVA):                 Yes
  Single to double precision performance:   32 : 1
  Supports compute pre-emption:             Yes
  Supports cooperative launch:              Yes
  Supports multi-device cooperative launch: Yes
  PCI bus/location:                         60/0
  Compute mode:                             Default
    Multiple contexts are allowed on the device simultaneously
```
</details>

**Comment by dpvanbalen** [comment]
I'm pretty sure `permute` is supposed to have ambiguous evaluation order, which is why the docs require the combination function to be both associative and commutative. This would argue the bug lies in the use of `permute` with a function that is not indifferent to the evaluation order, but perhaps there should (also) be a `permute` variant that is deterministic

**Comment by tmcdonell** [comment]
yes the example program certainly has non-deterministic behaviour, so that's not a bug. but if the `expand` function relies on this then that is definitely broken and needs to be fixed.

**Comment by robbert-vdh** [comment]
You're both 100% correct! I just stumbled upon this while dissecting `expand` and I did not even consider that `permute const` is not supposed to be deterministic here. I'll close this since permute is only used this way in expand.
