### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by tmcdonell** [AccelerateHS/accelerate-llvm#80]
Add support for running accelerate-llvm-native on Apple silicon Macs.

Current status:
- [ ] Purchase/get access to an apple silicon mac
- [ ] Update Homebrew formula to support ARM (llvm-hs/homebrew-llvm#21)
- [x] Update compiler/linker (@robbert-vdh has incidentally done probably the lions share of this as part of his work; we just need to merge that in)
- [ ] Test, debug, etc.

**Additional context**
Original email here: https://groups.google.com/g/accelerate-haskell/c/d_Drv-9Uq7w/m/XvSYk_VzCQAJ

**Comment by robbert-vdh** [comment]
> Update compiler/linker

I haven't tested it on anything other than Linux, but all of that should in theory indeed work on any Unix-like system in my `feature/tracy-annotations` branch since we're just piggy backing off of the operating system's linker and dynamic linker.

**Comment by kenranunderscore** [comment]
Hey! I don't fully understand the status of the issue. I'm reading it as "in theory it could work already", is that correct?

We're currently trying to build `accelerate-llvm` with GHC 9.0.2 and seeing some errors. Should I even report them if this effort is still ongoing? If yes, should I create a new issue or attach traces here?

**Comment by tmcdonell** [comment]
Ah sorry I didn't see your message. I just updated everything to LLVM-15 and tested it works on M1. It could still probably be improved because it doesn't make a distinction between the P and E-cores, but it should at least work correctly. If you find any errors please open a new issue.

Thanks for your patience!
