### ISSUE TITLE
stack installed it as a local package

### ISSUE THREAD

**Issue by chmlxj** [AccelerateHS/accelerate-llvm#9]
I git cloned into ~/accelerate-llvm/, then I "stack install" the package, it installed the package locally, i.e. the installation path is somewhere under ~/accelerate-llvm/...., not as a global package install.
Is there a way to fix this?

**Comment by tmcdonell** [comment]
I don't think so. I'd like to get 'accelerate-llvm' and friends onto the stackage list so that it would be installed globally, but I'm not sure on the procedure for that. I don't know what their policy is for packages that have external library dependencies is either.

**Comment by tmcdonell** [comment]
c.f. https://github.com/AccelerateHS/accelerate/issues/344
