### ISSUE TITLE
optimized matmul example

### ISSUE THREAD

**Issue by nyck33** [AccelerateHS/accelerate-llvm#99]
I just discovered this while trying to learn Haskell for the 25th time in a span of about 3 years.
I see things like: https://github.com/siboehm/SGEMM_CUDA
and in MLIR Python bindings:

https://colab.research.google.com/drive/1RNFSPtD0o9aJFwnqKQSRabODtSZjwPN1#scrollTo=lBaiwflQKR4Q

but are there any examples of optimized matmul using this library?

**Comment by tmcdonell** [comment]
There are bindings to CUBLAS here for example, if that is what you want? https://github.com/tmcdonell/accelerate-blas
You could modify to target cutlass etc. in a similar way, if you wish

**Comment by nyck33** [comment]
@tmcdonell thanks so much for pointing it out for me.

**Comment by tmcdonell** [comment]
No problem, good luck!
BTW there is a (incomplete) [list of additional components](https://github.com/AccelerateHS/accelerate?tab=readme-ov-file#additional-components) that you might also be interested in:
